name: moon_phases_extra
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/karim-mvp/moon_phases_extra.git

environment:
  sdk: ^3.7.0-323.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  simple_ruler_picker: ^0.1.1
  wheel_slider: ^1.2.2
  intl: ^0.20.2
  table_calendar: ^3.2.0
  provider: ^6.1.5+1
  moon_phase: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/full_moon.png
